ci: update GitHub Actions workflow for commitlint and actionlint
- Renamed job names for clarity and consistency.
- Changed commitlint configuration file extension from .js to .mjs.
- Updated actionlint action to a newer version and added a summary step to report results.

diff --git a/.github/workflows/pr-validation.yml b/.github/workflows/pr-validation.yml
--- a/.github/workflows/pr-validation.yml
+++ b/.github/workflows/pr-validation.yml
@@ -11,22 +11,34 @@ permissions:
 
 jobs:
   commitlint:
-    name: Commit messages (commitlint)
+    name: Commit Messages
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
       # Validate commits in PR (also works for forks)
-      - name: Lint commits in PR
+      - name: Commitlint
         uses: wagoid/commitlint-github-action@v6
         with:
-          configFile: commitlint.config.js
+          configFile: commitlint.config.mjs
 
   actionlint:
-    name: Workflow syntax (actionlint)
+    name: Workflow Syntax
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
-      - name: Lint GitHub workflows
-        uses: rhysd/actionlint@v1
+      - name: Actionlint
+        id: actionlint
+        uses: raven-actions/actionlint@v2
+      
+      - name: Actionlint Summary
+        if: ${{ steps.actionlint.outputs.exit-code != 0 }}  # example usage, do echo only when actionlint action failed
+        run: |
+          echo "Used actionlint version ${{ steps.actionlint.outputs.version-semver }}"
+          echo "Used actionlint release ${{ steps.actionlint.outputs.version-tag }}"
+          echo "actionlint ended with ${{ steps.actionlint.outputs.exit-code }} exit code"
+          echo "actionlint ended because '${{ steps.actionlint.outputs.exit-message }}'"
+          echo "actionlint found ${{ steps.actionlint.outputs.total-errors }} errors"
+          echo "actionlint checked ${{ steps.actionlint.outputs.total-files }} files"
+          echo "actionlint cache used: ${{ steps.actionlint.outputs.cache-hit }}"
+          exit ${{ steps.actionlint.outputs.exit-code }}
